import React from 'react';
import { motion } from 'framer-motion';

const TermsOfService: React.FC = () => {
  return (
    <div className="min-h-screen pt-20 pb-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-dark-900 border border-white/5 rounded-2xl p-8 md:p-12"
        >
          <h1 className="text-3xl font-display font-bold text-white mb-8">Terms of Service</h1>
          <div className="space-y-6 text-slate-400 leading-relaxed">
             <p>Last updated: {new Date().toLocaleDateString()}</p>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing and using Frame2Code, you accept and agree to be bound by the terms and provision of this agreement.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. Use License</h2>
              <p>Permission is granted to temporarily use Frame2Code for personal, non-commercial transitory viewing and code generation. This is the grant of a license, not a transfer of title.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. AI-Generated Code Disclaimer</h2>
              <p>The code generated by Frame2Code is provided "as is". We make no warranties regarding the accuracy, reliability, or security of the code produced. You are responsible for reviewing and testing any code before using it in production environments.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">4. Limitations</h2>
              <p>In no event shall Frame2Code or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit) arising out of the use or inability to use the materials on Frame2Code.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">5. Governing Law</h2>
              <p>Any claim relating to Frame2Code's website shall be governed by the laws of the website owner's home jurisdiction without regard to its conflict of law provisions.</p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsOfService;